worker_processes auto;
events { worker_connections 1024; }

http {
  client_max_body_size 10m;

  server {
    listen 80;
    location = /healthz { return 200 "ok\n"; }

    add_header Access-Control-Allow-Origin * always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;


    if ($request_method = OPTIONS) {
      return 204;
    }


    location /api/app/ {
      proxy_set_header Host $host;
      proxy_pass http://recruitmentapp:3000/;
    }
  }
}