apiVersion: v1
kind: Secret
metadata: 
  name: hr-app-secret
  namespace: noel-ns
type: Opaque
stringData:
  MONGO_URI: mongodb://rootuser:rootpassword@mongodb:27017/hr_system?authSource=admin


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-app-configmap
  namespace: noel-ns
data:
  NODE_ENV: production
  PORT: "3000"
  DB_NAME: hr_system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app
  namespace: noel-ns
  labels:
    app: hr
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vapp
    spec:
      containers:
        - name: fitness-app
          image: nmc9812/recruitmentapp:v1.1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: hr-app-configmap
                key: PORT
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: hr-app-secret
                key: MONGO_URI
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: hr-app-configmap
                key: DB_NAME


---

apiVersion: v1
kind: Service
metadata:
  name: hr-app
  namespace: noel-ns
spec:
  selector:
    app: vapp
  ports:
    - port: 3001
      targetPort: 3000
      protocol: TCP
  type: NodePort

      