apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-app-configmap
data:
  NODE_ENV: "production"
  PORT: "3000"
  MONGO_URI: "mongodb://rootuser:rootpassword@mongo-service:27017/hr_system?authSource=admin"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: HR-app
  namespace: noel-ns
  labels:
    app: HR
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vapp
    spec:
      containers:
        - name: fitness-app
          image: nmc9812/recruitmentapp:v1.1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
          - name: PORT
            valeFrom:
              configMapKeyRef:
                name: hr-app-configmap
                key: PORT
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: hr-app-configmap
                key: MONGO_URI


---

apiVersion: v1
kind: Service
metadata:
  name: HR-app
  namespace: noel-ns
spec:
  selector:
    app: vapp
  ports:
    - port: 3001
      targetPort: 3000
      protocol: TCP
  type: NodePort

      