apiVersion: v1
kind: ConfigMap
metadata:
  name: hr-mongo-configmap
  namespace: noel-ns
data:
  MONGO_INITDB_ROOT_USERNAME: "rootuser"
  MONGO_INITDB_ROOT_PASSWORD: "rootpassword"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: noel-ns
  labels:
    app: mongo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongodb
          image: mongo:8
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: hr-mongo-configmap
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: hr-mongo-configmap
                key: MONGO_INITDB_ROOT_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: noel-ns
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  type: NodePort
  

      